export const TypesNotification = {
    'SUCCESS_ACCOUNT_VERIFIED': 'SUCCESS_ACCOUNT_VERIFIED',
    'INFORMATION' : 'INFORMATION',
    'MARKETING' : 'MARKETING',
    'SUCCESS_KYC_VERIFIED' : 'SUCCESS_KYC_VERIFIED',
    'SUCCESS_TRANSFER_FUNDS' : 'SUCCESS_TRANSFER_FUNDS',
    'SUCCESS_DEPOSIT_WALLET' : 'SUCCESS_DEPOSIT_WALLET',
    'SUCCESS_DEPOSIT_CARD' : 'SUCCESS_DEPOSIT_CARD',
    'PAYMENT_FAILED' : 'PAYMENT_FAILED',
    'SUCCESS_ADD_SECOND_NUMBER' : 'SUCCESS_ADD_SECOND_NUMBER',
    'SUCCESS_VERIFY_SECOND_NUMBER' : 'SUCCESS_VERIFY_SECOND_NUMBER',
    'SUCCESS_CREATING_CARD' : 'SUCCESS_CREATING_CARD',
    'ERROR' : 'ERROR',
    'SUCCESS_MODIFY_PASSWORD' : 'SUCCESS_MODIFY_PASSWORD',
    'SUCCESS_MODIFY_ACCOUNT_INFORMATIONS' : 'SUCCESS_MODIFY_ACCOUNT_INFORMATIONS',
    'DELETE_ACCOUNT' : 'DELETE_ACCOUNT',
    'ENABLED_ACCOUNT' : 'ENABLED_ACCOUNT',
    'DISABLED_ACCOUNT' : 'DISABLED_ACCOUNT'
}